### ISSUE TITLE
how do I use this?

### ISSUE THREAD

**Issue by electroglyph** [LoganDark/stackblur-iter#12]
Sorry, new to Rust.  I have a vector of floats from -1.0 to 1.0 that i'm trying to blur.  How would I do that?  The demo code doesn't match the current function signatures, which require 4 arguments.

**Comment by LoganDark** [comment]
> The demo code doesn't match the current function signatures, which require 4 arguments.

Keep in mind that in the demo, the `stackblur` crate is an old legacy thing, not this crate. The call to `stackblur-iter` is the `par_simd_blur_srgb` call.

The basic usage of the generic `blur` function is to pass it an `&mut ImgRefMut<T>` where T can be anything, a blur radius, and a function to convert T to and from an actual `StackBlurrable` implementer. `StackBlurrable` is the trait for some value that is possible to blur using `stackblur-iter`, and is just a bunch of other traits to implement.

Basically you create a newtype wrapper around a float that implements the needed traits (namely multiplying and dividing by usize directly, which floats don't normally implement) in order for `StackBlurrable` to appear on it, and pass functions that wrap/unwrap a float in that newtype when you blur your vector with `blur`.

Try asking others for help or reply again here if you need extra, I have to go for a moment but figured I'd leave this reply anyway.

By the way, you can use the `StackBlur` struct directly over any `Iterator<Item = T>` (where `T: StackBlurrable`), though I would recommend `blur` since it will safely modify something in-place.

**Comment by electroglyph** [comment]
Thanks a lot for the reply.

edit: works great!  thanks a ton
